export const BookingStatus = {
  SERVICE_SELECTED: "SERVICE_SELECTED",
  ADDRESS_PENDING: "ADDRESS_PENDING",
  SLOT_SELECTION_PENDING: "SLOT_SELECTION_PENDING",
  CONFIRMED: "CONFIRMED",
  TECHNICIAN_ASSIGNED: "TECHNICIAN_ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  RESCHEDULED: "RESCHEDULED",
  PENDING_PAYMENT: "PENDING_PAYMENT",
} as const;

export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];
