export const Screen = {
  SERVICE_CATEGORY: "SERVICE_CATEGORY",
  SERVICE_DETAILS: "SERVICE_DETAILS",
  ADDRESS_ENTRY: "ADDRESS_ENTRY",
  SERVICEABILITY_CHECK: "SERVICEABILITY_CHECK",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SLOT_SELECTION: "SLOT_SELECTION",
  ADDITIONAL_DETAILS: "ADDITIONAL_DETAILS",
  BOOKING_REVIEW: "BOOKING_REVIEW",
  BOOKING_CONFIRMATION: "BOOKING_CONFIRMATION",
  BOOKING_DETAILS: "BOOKING_DETAILS",
} as const;

export type Screen = (typeof Screen)[keyof typeof Screen];
