export const ProductCategory = {
  Electronics: 'Electronics',
  Clothing: 'Clothing',
  Home: 'Home',
  Books: 'Books',
  Beauty: 'Beauty',
  Sports: 'Sports',
  Toys: 'Toys',
  Automotive: 'Automotive',
  Grocery: 'Grocery',
  Health: 'Health',
  Jewelry: 'Jewelry',
  Music: 'Music',
  Office: 'Office',
  PetSupplies: 'PetSupplies',
  Shoes: 'Shoes',
  Tools: 'Tools',
  VideoGames: 'VideoGames',
  Watches: 'Watches',
  Baby: 'Baby',
  Garden: 'Garden',
  Industrial: 'Industrial',
  Luggage: 'Luggage',
  Furniture: 'Furniture',
  Art: 'Art',
  Collectibles: 'Collectibles',
  Appliances: 'Appliances',
  MusicalInstruments: 'MusicalInstruments',
  Software: 'Software',
  Video: 'Video',
} as const;

export type ProductCategory = (typeof ProductCategory)[keyof typeof ProductCategory];
